### PR TITLE
CPP-538 Update to support Webpack 5 instead

### LINKED ISSUE #4: Webpack 5 compatibility
hey Matt 😄 Page Kit currently doesn't work with Webpack 5 because of this plugin (some deprecation warnings and a renamed property):

```
(node:29059) [DEP_WEBPACK_MAIN_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: MainTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(node:29059) [DEP_WEBPACK_CHUNK_TEMPLATE_RENDER_MANIFEST] DeprecationWarning: ChunkTemplate.hooks.renderManifest is deprecated (use Compilation.hooks.renderManifest instead)
(node:29059) [DEP_WEBPACK_MAIN_TEMPLATE_HASH_FOR_CHUNK] DeprecationWarning: MainTemplate.hooks.hashForChunk is deprecated (use JavascriptModulesPlugin.getCompilationHooks().chunkHash instead)
(node:29059) [DEP_WEBPACK_COMPILATION_NORMAL_MODULE_LOADER_HOOK] DeprecationWarning: Compilation.hooks.normalModuleLoader was moved to NormalModule.getCompilationHooks(compilation).loader

/Users/kara.brightwell/Work/dotcom-tool-kit/packages/webpack/node_modules/webpack/lib/Module.js:1059

throw new Error(^

Error: Module.used was refactored (use ModuleGraph.setUsedExports instead)
```

i seem to remember this plugin wouldn't be needed with Webpack 5, but i can't find any info about that, do you happen to know?

if it is required, we can work on a PR to make it compatible, but i was wondering if you'd be willing to transfer this repo to us so we can properly maintain it (it looks like Page Kit is [the only user](https://github.com/search?q=DisableTreeShakingForChunk&type=code))?

### PR DESCRIPTION
**Pull request by ivomurrell**
The Webpack plugin ecosystem is undocumented so I've based the work on the internal work linked in the PR, #4, i.e.:

- https://github.com/webpack/webpack/blob/main/lib/FlagAllModulesAsUsedPlugin.js
- https://github.com/webpack/webpack/issues/10025

Support for Webpack 4 will be dropped so this will be released in a new major version.

Closes #4

### CODE REVIEW

File: src/markAsUsed.js [hunk 1]
```diff
@@ -1,5 +1,8 @@
-module.exports = (m) => {
-  m.used = true
-  m.usedExports = true
-  m.buildMeta.providedExports = true
+module.exports = (m, mg, rt) => {
```
Comment (apaleslimghost) [inline src/markAsUsed.js:1]: **nitpick**: would prefer more descriptive variable names here

**Review by apaleslimghost — APPROVED** [review]
i have no idea what's going on here; but lgtm! two non blocking comments
